#!/bin/sh

loadConfig() {
  if [ -f "$config" ]; then
    source "$config"
  else
    mkdir -p "$(dirname "$config")"
    touch "$config"
  fi
}

help() {
  printf "ISP Manager 1.0, a CLI tool for captive portals\n"
  printf "Usage: ispmgr [OPTION]...\n\n"
  printf "init        start the setup wizard"
  printf "\n--help      display this help section\n"

  exit 0
}

init() {
  read -rp "Captive Portal URL: " url
  echo "firstRun=1" >> "$config"
  echo "url=$url" >> "$config"
  loadConfig
}

config="$HOME/.config/ispmgr.conf"
loadConfig

if [ "$firstRun" = "" ] && [ "$1" = "" ]; then
  printf "ispmgr: run setup first\n"
  printf "Try 'ispmgr --help' for more options.\n"
  exit 0

elif [ "$firstRun" = "" ] && [ "$1" = "--help" ]; then
  help

elif [ "$firstRun" = "" ] && [ "$1" != "init" ]; then
  printf "ispmgr: unrecognized option '"$1"'\n"
  printf "ispmgr: run setup first\n"
  printf "Try 'ispmgr --help' for more options.\n"
  exit 0
fi

case $1 in
  'init')
    init
  ;;

  '--help')
    help
  ;;
  
  *)
    printf "ispmgr: unrecognized option '"$1"'\n"
    printf "Try 'ispmgr --help' for more options.\n"
    exit 0
  ;;
esac