#!/bin/sh

loadConfig() {
  if [ -f "$config" ]; then
    source "$config"
  fi
}

help() {
  printf "ISP Manager 1.0, a CLI tool for captive portals\n"
  printf "Usage: ispmgr [OPTION]...\n\n"
  printf " --help  display this help section\n"
  exit 0
}

config="$HOME/.config/ispmgr.conf"
loadConfig

if [ "$firstRun" = "" ] && [ "$1" = "" ]; then
  mkdir -p "$HOME/.config/" && touch "$HOME/.config/ispmgr.sh"
  printf "ispmgr: run setup first\n"
  printf "Try 'ispmgr --help' for more options.\n"
  exit 0

elif [ "$firstRun" = "" ] && [ "$1" = "--help" ]; then
  help

elif [ "$firstRun" = "" ] && [ "$1" != "init" ]; then
  printf "ispmgr: unrecognized option '"$1"'\n"
  printf "ispmgr: run setup first\n"
  printf "Try 'ispmgr --help' for more options.\n"
  exit 0
fi
